name: 筛选并提交 Hosts 结果

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  filter-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 保留凭据，用于后续推送

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行筛选脚本
        run: python filter_hosts.py  # 生成 filtered_hosts.txt

      - name: 检查文件是否生成
        run: |
          if [ ! -f "filtered_hosts.txt" ]; then
            echo "ERROR: 未生成 filtered_hosts.txt"
            exit 1
          fi

      - name: 配置 Git 信息
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: 提交文件到仓库
        run: |
          # 检查是否有变更
          git add filtered_hosts.txt
          git diff --quiet --staged || (git commit -m "自动更新筛选后的 hosts 列表 $(date +'%Y-%m-%d')" && git push origin HEAD:main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用内置令牌授权推送
